<a href="https://colab.research.google.com/github/rajatkmitra/authored/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover some of the moste fundamentals of tensors using Tensorflow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from Tensors
* Manipulating Tensors
* Tensors & NumPy
* Using @tf.functions (a wasy to speed up your regular Python functions)
* Using GPU with Tensorflow (or TPUs)
* Exercise to try yourself


# Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [3]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check the number of dimensions of a tensor (ndim stands for the number of dimensions)
scalar.ndim

0

In [12]:
#Create a vectos
vector = tf.constant([[10,10]])
vector

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10, 10]], dtype=int32)>

In [6]:
#Check the dimensions of out vector
vector.ndim 

1

In [9]:
#Create a matrix (has more than 1 dimension)
matrix = tf.constant( [[10, 7],
                      [7,10]] )
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [16]:
#Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [17]:
another_matrix.ndim

2